---
title: "Spider_Chart_OC_index"
output: html_document
date: "2023-02-04"
---

#installing packages
```{r}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(fmsb)
library(RColorBrewer)
```

```{r}
global_oc_index_spider <- read_csv(here("data/global_oc_index_2021_sids_category.csv"))
```


```{r}
data <- as.data.frame(matrix( sample( 2:20 , 10 , replace=T) , ncol=10))
colnames(data) <- c("criminality" , "english" , "biology" , "music" , "R-coding", "data-viz" , "french" , "physic", "statistic", "sport" )
```


```{r}
# To use the fmsb package, I have to add 2 lines to the dataframe: the max and min of each topic to show on the plot!
data <- rbind(rep(20,10) , rep(0,10) , data)
```


```{r}
# The default radar chart 
radarchart(data)
```

```{r}
global_oc_index_spider <- global_oc_index_spider %>% 
  clean_names() 



global_oc_index_spider <- global_oc_index_spider %>%
  mutate(overall_score = resilience - criminality)
```


```{r}
global_oc_index_spider_sids <- global_oc_index_spider %>% 
  filter(sids_category == "sids")
  
```


```{r}
sids_overall_score_plot <- ggplot(data = global_oc_index_spider_sids, aes(x = overall_score,
                                                                          y = reorder(country, overall_score),
                                                                          fill = region)) +
  geom_bar(stat = "identity") +
  scale_fill_brewer(palette = "Paired")

sids_overall_score_plot
```


```{r}
global_oc_index_spider_sids_criminality <- global_oc_index_spider_sids %>% 
  select(country, criminality)
```


```{r}
global_oc_index_spider_sids_criminality_wider <- global_oc_index_spider_sids_criminality %>% 
  pivot_wider(names_from = country,
              values_from = criminality)
```

```{r}
radar_data <- rbind(rep(8,4) , rep(0,8) , global_oc_index_spider_sids_criminality_wider)
```


```{r}
radar_data <- radar_data[, order(radar_data[3, ])]
```

```{r}
radar_data <- radar_data[, rev(order(radar_data[3,]))]
```


```{r}
radarchart(radar_data, pfcol = "lavender")
```


#Customizing the Spider Plot
```{r}
colors_border=c( rgb(0.2,0.5,0.5,0.9), rgb(0.8,0.2,0.5,0.9) , rgb(0.7,0.5,0.1,0.9) )
colors_in=c( rgb(0.2,0.5,0.5,.8), rgb(0.8,0.2,0.5,.8) , rgb(0.7,0.5,0.1,.8) )
```


```{r}
radarchart(radar_data, axistype=1 , pcol=colors_border , pfcol=colors_in , plwd=3 , plty=1, cglcol="dark grey", cglty=1, axislabcol="grey", caxislabels=seq(0,20,5), cglwd=0.95,vlcex=0.8)

legend(x=0.85, y=1, legend = c("Shirley", "Sonia"), bty = "n", pch=20 , col=colors_border , text.col = "black", cex=0.9, pt.cex=1.6)
```


```{r}

```


